package hyperlight-wasm-examples:calculator;

interface add {
    add: func(x: u32, y: u32) -> u32;
}

world adder {
    export add;
}

interface subtract {
    subtract: func(x: u32, y: u32) -> u32;
}

interface multiply {
    multiply: func(x: u32, y: u32) -> u32;
}

world subtractor {
    export subtract;
}

interface calculate {
    enum op {
        add,
        subtract,
        multiply,
    }
    evalexpression: func(op: op, x:u32, y:u32) -> u32;
}

world calculator {
    export calculate;
    import add;
    import subtract;
    import multiply;
}